BI-2486: upload mongosql_auth.so to a task indifference place
mongodb/mongosql-auth-c pull request #8
Opened 2020-02-21 21:20 UTC by huan-Mongo

The uploaded file will be used in Mongosqld testing. A location across all tasks will prevent the file from expiring too often.

2020-02-21 23:20 UTC, rychipman requested changes
Just one request!

2020-02-21 23:20 UTC, rychipman commented on .evg.yml
> +        display_name: "mongosql_auth.so"
Can we also do this for the dll?

2020-02-23 17:13 UTC, huan-Mongo commented on .evg.yml
> +        display_name: "mongosql_auth.so"
Sure, added the dll one

2020-02-23 17:14 UTC, huan-Mongo commented
I fixed nohup issue during MacOS test. But there is another issue caused by openssl version which I couldn't find a solution. So I created ticket https://jira.mongodb.org/browse/BI-2487

2020-02-24 18:06 UTC, rychipman approved these changes
LGTM

2020-02-24 18:10 UTC, merged